---
header-includes:
  - \usepackage{booktabs}
  - \usepackage[table]{xcolor}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \pagenumbering{gobble}
output:
  pdf_document: default
  keep_tex: true
classoption: table
params:
  heading: XX
  caption: YY
  data: df
  id: 1
  name: ''
  logo: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(kableExtra.latex.load_packages = FALSE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(png)
```
## `r params$heading`
### `r params$caption`

```{r echo=FALSE, results='asis'}
kable(params$data, "latex", align = "c", booktabs = T, longtable = T) %>%
  group_rows("Specimen Received", 1, 3) %>%
  group_rows("Unsatisfactory Specimens", 4, 14) %>%
  group_rows("Missing Information at specimen release", 15, 16) %>%
  group_rows("Early/Transfused Specimens", 17, 18) %>%
  
  column_spec(1, width = "15em") %>%
  column_spec(2:3, width = "14em") %>%
  kable_styling(position = 'left', latex_options = c("striped")) %>%

    footnote(number = c("Early collection may be appropriate in some instances such as if infant will be transferred or discharged prior to 24 hour. Also if an infant will receive a transfusion before 24 hours, an early collection prior to transfusion is appropriate and recommended.", "Transfused before collection may be appropriate if it is a repeat collection on an infant that had previous collection (such as initial was an early collection)."), threeparttable = T)
```
```{r echo=FALSE, fig.width = 12, fig.height = 5}
   pp <- readPNG(params$logo)
   plot.new()
   rasterImage(pp,0,0,1,1, interpolate=FALSE)
```
